Azure Snapshot Repository
elastic/puppet-elasticsearch pull request #1087
Opened 2020-06-02 12:00 UTC by jtbrush56

Pull request acceptance prerequisites:

- [ ] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [ ] Rebased/up-to-date with base branch
- [ ] Tests pass
- [ ] Updated CHANGELOG.md with patch notes (if necessary)
- [ ] Updated CONTRIBUTORS (if attribution is requested)

2020-06-02 12:00 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-06-08 15:55 UTC, fatmcgav commented
Jenkins test this please

2020-06-08 16:03 UTC, fatmcgav requested changes
@jtbrush56 Thank you for taking the time to make these additions. 

A few comments that need addressing.
I'd also like to see the new properites added to the unit tests.[1][2]

Also, could you add an example to the README.md[3]

[1] https://github.com/elastic/puppet-elasticsearch/blob/master/spec/unit/type/elasticsearch_snapshot_repository_spec.rb
[2] https://github.com/elastic/puppet-elasticsearch/blob/master/spec/unit/provider/elasticsearch_snapshot_repository/ruby_spec.rb
[3] https://github.com/elastic/puppet-elasticsearch#snapshot-repositories

2020-06-08 16:03 UTC, fatmcgav commented on manifests/snapshot_repository.pp
> +#   Location of snapshots.
This field is still mandatory when `type => "fs"`, so we should state that.

2020-06-08 16:03 UTC, fatmcgav commented on manifests/snapshot_repository.pp
> +  Optional[String]                $client                = undef,
Can you sort out the alignment on these lines? Should all align on `=`.

2020-06-08 18:32 UTC, jtbrush56 commented
updated with requested changes.

2020-06-09 10:40 UTC, fatmcgav requested changes
It looks like `rubocop` is still complaining about trailing whitespace on https://github.com/elastic/puppet-elasticsearch/pull/1087/files#diff-9240f318e7e1ac50308c77dfa32622ddR49-R54

You should be able to test `rubocop` locally by running `bundle exec rake rubocop`.

2026-07-30 20:58 UTC, closed without merging